services:
  db:
    image: postgres:15-alpine
    container_name: postgres_universidad
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: reservas_db
    ports:
      - "5432:5432"
    volumes:
      - ./sql/esquema.sql:/docker-entrypoint-initdb.d/esquema.sql

  backend:
    build: .
    container_name: backend_reservas
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}