version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_universidad
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: reservas_db
    ports:
      - "5432:5432"